title: Stefanie Mittman
logo: /assets/img/logo.png
description:  Graduate Student MS Supply Chain Analytics
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
